[webservers]
web-1 ansible_host=10.0.1.16 fqdn=web-1.ru-central1.internal
web-2 ansible_host=10.0.1.35 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=10.0.1.8 fqdn=main.ru-central1.internal
replica ansible_host=10.0.1.23 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=93.77.191.45 fqdn=storage.ru-central1.internal
